language: python
python:
    - 2.7
    - 3.5

env:
    matrix:
        - THREADING=
        - THREADING="gevent gevent-websocket"
        - THREADING="eventlet"

cache:
    - pip

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install socketio-client
    - echo $THREADING | xargs -r pip install

before_script:
    - python -m flake8 .
    - ./manage.py db init
    - ./manage.py db migrate
    - ./manage.py db upgrade

script:
    - nosetests .
